version: '3.8'
services:
  nginx:
    image: seu_nginx_image
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Estas variáveis devem ser definidas aqui se você as usa em um template Nginx
      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PORT: 8082
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 8083
      # ... e assim por diante para todos os seus serviços
    depends_on:
      - auth-service
      - user-service
      # ...
    networks:
      - minha_rede_app # Ambos os serviços devem estar na mesma rede

  auth-service:
    image: seu_auth_service_image
    networks:
      - minha_rede_app

  user-service:
    image: seu_user_service_image
    networks:
      - minha_rede_app

networks:
  minha_rede_app:
    driver: bridge