version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - legalconnect-network
    depends_on:
      - db-global

  db-global:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: jusplatform_db  # Corrigido: removido o "P" extra
      POSTGRES_USER: jususer
      POSTGRES_PASSWORD: juspassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
      - db-global-data:/var/lib/postgresql/data
    networks:
      - legalconnect-network

volumes:
  db-global-data:

networks:
  legalconnect-network:
    driver: bridge